<template>
  <article class="diff" :class="{ compact }"><div class="diff-title"><strong>{{ item.title }}</strong><el-tag>{{ displayLabel(item.diff_type) }}</el-tag></div><div class="sides"><div><b>{{ leftLabel }}</b><small>{{ locations(item.baseline) }}</small><p class="before">{{ item.baseline?.text || '—' }}</p></div><div><b>当前文件</b><small>{{ locations(item.target) }}</small><p class="after">{{ item.target?.text || '—' }}</p></div></div></article>
</template>
<script setup lang="ts">
import type { DiffItem, DiffSide, DocumentLocation } from '../../api/types'
import { displayLabel } from '../../utils/labels'
withDefaults(defineProps<{ item: DiffItem; leftLabel?: string; compact?: boolean }>(), { leftLabel: '基准文件', compact: false })
function location(value?: DocumentLocation){if(!value)return '无对应位置';return [value.page&&`第 ${value.page} 页`,value.paragraph_index!=null&&`段落 ${value.paragraph_index}`,value.table_index!=null&&`表格 ${value.table_index}`,value.row!=null&&`行 ${value.row}`,value.column!=null&&`列 ${value.column}`].filter(Boolean).join(' · ')||'结构位置未知'}
function locations(side?: DiffSide){const values=side?.locations?.length?side.locations:(side?.location?[side.location]:[]);if(!values.length)return '无对应位置';const first=location(values[0]);const last=location(values[values.length-1]);return first===last?first:`${first} → ${last}（共 ${values.length} 处）`}
</script>
<style scoped>.diff{border:1px solid var(--report-border);border-radius:9px;padding:14px;margin:10px 0;background:var(--report-surface)}.diff.compact{margin-top:12px;background:var(--report-surface);padding:11px}.diff-title{display:flex;justify-content:space-between;gap:10px}.diff-title strong{font-size:13px}.sides{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.sides>div{background:var(--report-surface-2);padding:11px;border-radius:7px;min-width:0}.sides b{font-size:12px}.sides small{display:block;color:var(--report-text-3);margin-top:4px;font-size:11px}.sides p{overflow-wrap:anywhere;margin:7px 0 0;font-size:13px}.before{text-decoration:line-through;text-decoration-color:var(--report-danger);color:var(--report-text-2)}.after{background:#fff1b8;color:var(--report-text)}@media(max-width:700px){.sides{grid-template-columns:1fr}}</style>
