const labels: Record<string, string> = {
  DRAFT_REVIEW: '起草检查',
  FINAL_COMPARE: '放款阶段比对',
  PENDING: '等待处理',
  RUNNING: '处理中',
  SUCCEEDED: '成功',
  FAILED: '失败',
  CANCELLED: '已取消',
  QUEUED: '等待排队',
  DOWNLOADING: '下载文件',
  PARSING: '解析文档',
  OCR: 'OCR 识别',
  TEMPLATE_COMPARE: '模板比对',
  FACT_EXTRACTION: '事实抽取',
  CROSS_VALIDATE: '跨资料核对',
  RULE_CHECKING: '规则检查',
  VERSION_COMPARE: '版本比对',
  GENERATING_ADVICE: '生成建议',
  PERSISTING_RESULT: '保存结果',
  COMPLETED: '已完成',
  PASS: '通过',
  RISK_FOUND: '发现风险',
  REVIEW_REQUIRED: '需要人工复核',
  RULE_BASED: '规则比对',
  MOCK: '模拟执行',
  BASELINE: '基准文件',
  TARGET: '目标文件',
  TEMPLATE: '合同模板',
  REFERENCE: '参考资料',
  WARNING: '存在警告',
  ADDED: '新增内容',
  DELETED: '删除内容',
  MODIFIED: '内容修改',
  NUMERIC_CHANGED: '数值变更',
  TABLE_ROW_ADDED: '表格新增行',
  TABLE_ROW_DELETED: '表格删除行',
  TABLE_CELL_CHANGED: '表格单元格变更',
  HIGH: '高风险',
  MEDIUM: '中风险',
  LOW: '低风险',
  INFO: '提示',
  'python-docx': 'DOCX 解析器',
  'pdfplumber': 'PDF 解析器',
  'textin-document-parser': '外部文档解析器',
  'mock-parser': '模拟解析器',
}

export function displayLabel(value: string | null | undefined): string {
  if (!value) return '—'
  return labels[value] ?? value
}
