const labels: Record<string, string> = {
  DRAFT_REVIEW: '起草检查',
  FINAL_COMPARE: '放款阶段比对',
  PENDING: '等待处理',
  RUNNING: '处理中',
  SUCCEEDED: '成功',
  FAILED: '失败',
  CANCELLED: '已取消',
  QUEUED: '等待排队',
  DOWNLOADING: '下载文件',
  PARSING: '解析文档',
  OCR: 'OCR 识别',
  TEMPLATE_COMPARE: '模板比对',
  FACT_EXTRACTION: '事实抽取',
  CROSS_VALIDATE: '跨资料核对',
  RULE_CHECKING: '规则检查',
  VERSION_COMPARE: '版本比对',
  GENERATING_ADVICE: '生成建议',
  PERSISTING_RESULT: '保存结果',
  COMPLETED: '已完成',
  PASS: '通过',
  RISK_FOUND: '发现风险',
  REVIEW_REQUIRED: '需要人工复核',
  RULE_BASED: '规则比对',
  HYBRID: '规则 + 模型',
  PARSER_ONLY: '真实解析',
  MOCK: '模拟执行',
  BASELINE: '基准文件',
  TARGET: '目标文件',
  TEMPLATE: '合同模板',
  REFERENCE: '参考资料',
  WARNING: '存在警告',
  ADDED: '新增内容',
  DELETED: '删除内容',
  MODIFIED: '内容修改',
  NUMERIC_CHANGED: '数值变更',
  TABLE_ROW_ADDED: '表格新增行',
  TABLE_ROW_DELETED: '表格删除行',
  TABLE_CELL_CHANGED: '表格单元格变更',
  TABLE_STRUCTURE_EXPANDED: '表格结构发生变化',
  PAGE_MISSING: '页面内容缺失',
  CONTENT_BLOCK_MISSING: '连续内容缺失',
  DELETION_OR_MISSING: '删除 / 缺失',
  ADDITION_OR_CHANGE: '新增 / 变更',
  RULE_FAILED: '规则未通过',
  SOURCE_CONFLICT: '来源冲突',
  VERSION_CHANGE: '版本变化',
  TEMPLATE_INTEGRITY: '模板完整性',
  TEMPLATE_RELIABILITY: '模板可靠性',
  DOCUMENT_RELIABILITY: '文档可靠性',
  DOCUMENT_ALIGNMENT: '文档对齐',
  TEMPLATE_COMPLETENESS: '模板填写完整性',
  CAPABILITY_LIMITATION: '能力边界',
  FACT_CONSISTENCY: '跨资料事实一致性',
  CONSISTENT: '一致',
  CONFLICT: '冲突',
  MISSING: '未提及',
  NOT_MENTIONED: '未提及',
  UNCERTAIN: '不确定',
  FACT_MISSING: '部分来源缺失',
  FACT_UNCERTAIN: '事实证据不足',
  LEGACY_RESULT: '历史结果',
  PDF_EXTERNAL_PARSE_USED: '已使用外部 PDF 解析',
  PARSER_STRUCTURE_MISMATCH: '解析结构不一致',
  ALIGNMENT_UNRELIABLE: '对齐可靠性不足',
  TABLE_STRUCTURE_INCOMPATIBLE: '表格结构不兼容',
  DOCUMENT_PAIR_UNRELATED: '疑似文件配对错误',
  OCR_SINGLE_CHAR_VARIANCE: 'OCR 单字符差异',
  OCR_PLACEHOLDER_VARIANCE: 'OCR 金额占位符差异',
  OCR_READING_ORDER_VARIANCE: 'OCR 阅读顺序差异',
  OCR_LOW_CONFIDENCE_VARIANCE: 'OCR 低置信度差异',
  STRUCTURED: '结构化对齐',
  PAGE_FLAT: '页面文本降级对齐',
  'python-docx': 'DOCX 解析器',
  'pdfplumber': 'PDF 解析器',
  'textin-document-parser': '外部文档解析器',
  'mock-parser': '模拟解析器',
  UNKNOWN: '待自动识别',
  DRAFT_REVIEW_PARSE_ONLY: '仅完成真实解析',
  DRAFT_REVIEW_RULE_BASED_LIMITATION: '起草检查规则能力边界',
  TEMPLATE_FILL_ALLOWED: '模板允许填写',
  TEMPLATE_TABLE_STRUCTURE_EXPANDED: '模板表格结构已扩展',
  MOCK_RESULT: '模拟结果',
  PASSED: '通过',
  NOT_RUN: '尚未识别',
}

export function displayLabel(value: string | null | undefined): string {
  if (!value) return '—'
  return labels[value] ?? value
}
