from enum import StrEnum


class TaskType(StrEnum):
    DRAFT_REVIEW = "DRAFT_REVIEW"
    FINAL_COMPARE = "FINAL_COMPARE"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskStage(StrEnum):
    QUEUED = "QUEUED"
    DOWNLOADING = "DOWNLOADING"
    PARSING = "PARSING"
    OCR = "OCR"
    TEMPLATE_COMPARE = "TEMPLATE_COMPARE"
    FACT_EXTRACTION = "FACT_EXTRACTION"
    CROSS_VALIDATE = "CROSS_VALIDATE"
    RULE_CHECKING = "RULE_CHECKING"
    VERSION_COMPARE = "VERSION_COMPARE"
    GENERATING_ADVICE = "GENERATING_ADVICE"
    PERSISTING_RESULT = "PERSISTING_RESULT"
    COMPLETED = "COMPLETED"


class Conclusion(StrEnum):
    PASS = "PASS"
    RISK_FOUND = "RISK_FOUND"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    FAILED = "FAILED"


class FileRole(StrEnum):
    TARGET = "TARGET"
    TEMPLATE = "TEMPLATE"
    REFERENCE = "REFERENCE"
    BASELINE = "BASELINE"


class ReferenceType(StrEnum):
    REVIEW_OPINION = "REVIEW_OPINION"
    PROJECT_CONFIRMATION = "PROJECT_CONFIRMATION"
    LEGAL_COMPLIANCE_REPORT = "LEGAL_COMPLIANCE_REPORT"
    OTHER = "OTHER"


class EventType(StrEnum):
    CREATED = "CREATED"
    STAGE_CHANGED = "STAGE_CHANGED"
    RETRY = "RETRY"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

